# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 06:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_data_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumericalData',
            fields=[
                ('dataID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('value', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Data',
        ),
    ]
