# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 05:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_auto_20170420_0500'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='source_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='data',
            name='time',
            field=models.IntegerField(default=1492665354582.1382, editable=False),
        ),
    ]
