# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 07:06
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_auto_20170420_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='data_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='data',
            name='time',
            field=models.IntegerField(default=1492671968809.115, editable=False),
        ),
        migrations.AlterField(
            model_name='source',
            name='source_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=200, primary_key=True, serialize=False),
        ),
    ]
