# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_auto_20170420_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='create_time',
            field=models.IntegerField(default=1492684562744.791),
        ),
        migrations.AlterField(
            model_name='data',
            name='source_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='data',
            name='upload_time',
            field=models.IntegerField(default=1492684562744.762, editable=False),
        ),
    ]
