# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_auto_20170420_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='create_time',
            field=models.IntegerField(default=1493200619841.713),
        ),
        migrations.AlterField(
            model_name='data',
            name='source_id',
            field=models.CharField(editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='data',
            name='upload_time',
            field=models.IntegerField(default=1493200619841.6892, editable=False),
        ),
    ]
